# Generated by Django 6.1.1 on 2026-10-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fa-spa', max_length=50, verbose_name='الأيقونة'),
        ),
    ]
