services:
  - type: web
    name: makeup-store
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.0"
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: makeup-store-db
          property: connectionString

databases:
  - name: makeup-store-db
    plan: free
    databaseName: makeup_store
    user: makeup_store
